# Generated by Django 5.2 on 2025-04-05 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetentionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Detention Reason',
                'verbose_name_plural': 'Detention Reasons',
            },
        ),
        migrations.CreateModel(
            name='DetentionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Detention Status',
                'verbose_name_plural': 'Detention Statuses',
            },
        ),
        migrations.CreateModel(
            name='PDLProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'PDL Profile',
                'verbose_name_plural': 'PDL Profiles',
            },
        ),
        migrations.CreateModel(
            name='DetentionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detention_start_date', models.DateField()),
                ('detention_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detention_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detention_instances', to='pdl.detentionreason')),
                ('detention_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detention_instances', to='pdl.detentionstatus')),
                ('pdl_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detention_instances', to='pdl.pdlprofile')),
            ],
        ),
    ]
