# Generated by Django 5.2 on 2025-04-05 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detentioninstance',
            name='detention_term_length',
            field=models.IntegerField(default=0, verbose_name='Detention Term Length'),
        ),
        migrations.AlterField(
            model_name='detentioninstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='detentioninstance',
            name='detention_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Detention End Date'),
        ),
        migrations.AlterField(
            model_name='detentioninstance',
            name='detention_reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detention_instances', to='pdl.detentionreason', verbose_name='Detention Reason'),
        ),
        migrations.AlterField(
            model_name='detentioninstance',
            name='detention_start_date',
            field=models.DateField(verbose_name='Detention Start Date'),
        ),
        migrations.AlterField(
            model_name='detentioninstance',
            name='detention_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detention_instances', to='pdl.detentionstatus', verbose_name='Detention Status'),
        ),
        migrations.AlterField(
            model_name='detentioninstance',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='detentioninstance',
            name='pdl_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detention_instances', to='pdl.pdlprofile', verbose_name='PDL Profile'),
        ),
        migrations.AlterField(
            model_name='detentioninstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='detentionreason',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='detentionreason',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='detentionstatus',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='detentionstatus',
            name='status',
            field=models.CharField(max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pdlprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pdlprofile',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='pdlprofile',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='pdlprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
