# Generated by Django 5.2 on 2025-04-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0002_detentioninstance_detention_term_length_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detentioninstance',
            options={'ordering': ['-detention_start_date'], 'verbose_name': 'Detention Instance', 'verbose_name_plural': 'Detention Instances'},
        ),
    ]
