# Generated by Django 5.2 on 2026-04-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0012_remove_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcondition',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('under_treatment', 'Under Treatment'), ('recovered', 'Recovered')], default='active', max_length=20),
        ),
    ]
