# Generated by Django 5.2 on 2026-04-19 11:50

from django.db import migrations


def seed_status_from_is_active(apps, schema_editor):
    HealthCondition = apps.get_model('pdl', 'HealthCondition')
    for hc in HealthCondition.objects.all():
        if not hc.status:
            hc.status = 'active' if hc.is_active else 'recovered'
            hc.save(update_fields=['status'])


def reverse_seed(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pdl', '0013_health_condition_status'),
    ]

    operations = [
        migrations.RunPython(seed_status_from_is_active, reverse_seed),
    ]
