# Generated by Django 5.2 on 2025-04-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationreason',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
