# Generated by Django 5.2 on 2025-04-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultationreason_description'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consultation',
            name='consultation_date_in_future',
        ),
    ]
